name: my_list
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  # Firebase
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6

  # Bloc
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc: ^8.1.4

  # Custom Repository
  user_repository:
    path: packages/user_repository

  task_repository:
    path: packages/task_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true